version: "3.9"
services:

  open-webui-demo:
    name: llm-mb_open-webui
    image: ghcr.io/open-webui/open-webui:main
    environment:
#      - DATA_DIR="/app/backend/data"
      - ENABLE_OLLAMA_API=False
      - ENABLE_OPENAI_API=True
      - OPENAI_API_KEY=sk-empty
      - OPENAI_API_BASE_URL=http://192.168.1.5:8686/v1
      - DEFAULT_MODELS="openai/iklcpp-Qwen3-Coder-30B-A3B-Instruct-cpu"
      - ENABLE_IMAGE_GENERATION=true
      - IMAGE_GENERATION_ENGINE=openai
      - IMAGE_GENERATION_MODEL=FLUX.2-klein-4B
      - IMAGE_SIZE=1024x1024
      - IMAGES_OPENAI_API_BASE_URL=http://192.168.1.5:8686/v1
      - IMAGES_OPENAI_API_KEY=dummy-key
      - WEBUI_AUTH=False
      - DEFAULT_USER_ROLE="admin"
      - HOST=0.0.0.0 # 127.0.0.1
      - PORT=33033
    entrypoint:
      bash
    command:
      start.sh
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    # network_mode: host 
    ports:
      - 33033:33033
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/open-webui:/app/backend/data

  open-webui-pipelines:
    name: llm-mb_open-webui-pipelines
    image: ghcr.io/open-webui/pipelines:main
    extra_hosts:
      - host.docker.internal:host-gateway
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/open-webui-pipelines:/app/pipelines:rw
