# llama.cpp server flags:
#   https://github.com/ggml-org/llama.cpp/tree/master/tools/server
# vLLM serve flags:
#   https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html
# TabbyAPI config:
#   https://github.com/theroyallab/tabbyAPI/wiki/02.-Server-options

version: "3.9"
services:

  llama-swapper:
    name: llm-mb_llama-swapper
    # build:
    #   context: env-llm-multi-backend/
    #   dockerfile: Containerfile
    image: bjodah/llama-swap
    ports:
      - "8686:8686"
    restart: unless-stopped
    devices:
      - "nvidia.com/gpu=all"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${HOST_CACHE_HUGGINGFACE:-~/.cache/huggingface}:/root/.cache/huggingface
      - ${HOST_CACHE_HUGGINGFACE:-~/.cache/huggingface}/hub:/models  # tabbyAPI...
      - ${HOST_CACHE_LLAMACPP:-~/.cache/llama.cpp}:/root/.cache/llama.cpp
      - ${HOST_CACHE_VLLM:-~/.cache/vllm}:/root/.cache/vllm
      - ./cache/torch_extensions:/root/.cache/torch_extensions
      - ./logs:/logs
      - ./configs:/configs
      - ./configs/tabby-api_tokens.yml:/opt/tabbyAPI/api_tokens.yml
      - ./configs/tabby-sampler_overrides:/opt/tabbyAPI/sampler_overrides
      - ./configs/tabby-templates/devstral-2-template.jinja:/opt/tabbyAPI/templates/devstral-2-template.jinja
      #- /opt/gguf-unsloth-maverick:/opt/gguf-unsloth-maverick  # my machine only...
    working_dir: "/"
    security_opt:
      - label:disable
    cap_add:
      - SYS_PTRACE  # gdb debugging
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HUGGING_FACE_HUB_TOKEN
      - HF_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - HF_HUB_ENABLE_HF_TRANSFER=1
      - LLAMA_ARG_THREADS=16
      - LLAMA_ARG_ENDPOINT_METRICS=1
      - LLAMA_ARG_ENDPOINT_SLOTS=1
      - LLAMA_API_KEY=sk-empty
      - LLAMA_ARG_NO_CONTEXT_SHIFT=1
      - LLAMA_ARG_NO_WEBUI=1
      - LLAMA_ARG_MAIN_GPU=0
      - LLAMA_ARG_SPLIT_MODE=none
      #- LLAMA_LOG_VERBOSITY=1
      - VLLM_API_KEY=sk-empty
    ipc: host
    entrypoint:
      /configs/autorestart-llama-swap.sh
    command: >
      /configs/llama-swap-config.yaml
      /logs/llama-swap.log


  memoryelaine:
    name: llm-mb_memoryelaine
    image: memoryelaine
    ports:
      - "8687:8687"
      - "8677:8677"
    restart: unless-stopped
    volumes:
      - ./configs/memoryelaine-config.yaml:/config.yaml
      - ./logs:/logs
    command: >
      serve --config /config.yaml

  multi-fim-proxy:
    name: llm-mb_fim-proxy
    image: multi-fim-proxy
    ports:
      - "8689:8689"
    #network: host
    environment:
      - LLAMA_API_KEY=sk-empty

  inferplex:
    name: llm-mb_inferplex
    image: inferplex
    ports:
      - "8688:8688"
    restart: unless-stopped
    volumes:
      - ./configs/inferplex-config.yaml:/inferplex-config.yaml
      - ./logs:/logs
    command: >
      --config /inferplex-config.yaml --upstream-base-url http://memoryelaine:8687/ --listen-addr 0.0.0.0 --listen-port 8688
