# llama.cpp server flags:
#   https://github.com/ggml-org/llama.cpp/blob/master/examples/server/README.md
# vLLM serve flags:
#   https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html
# TabbyAPI config:
#   https://github.com/theroyallab/tabbyAPI/wiki/02.-Server-options

version: "3.9"
services:

  llm-multi-backend:
    build:
      context: env-llm-multi-backend/
      dockerfile: Containerfile
    ports:
      - "8686:8686"
    devices:
      - "nvidia.com/gpu=all"
    volumes:
      - ${HOST_CACHE_HUGGINGFACE:-~/.cache/huggingface}:/root/.cache/huggingface
      - ${HOST_CACHE_HUGGINGFACE:-~/.cache/huggingface}/hub:/models  # tabbyAPI...
      - ${HOST_CACHE_LLAMACPP:-~/.cache/llama.cpp}:/root/.cache/llama.cpp
      - ./logs:/logs
      - ./configs:/configs
      - ./configs/tabby-api_tokens.yml:/api_tokens.yml
      - ./qwen2.5-VL-inference-openai:/phildougherty-qwen-vl-api
      - /opt/gguf-unsloth-maverick:/opt/gguf-unsloth-maverick  # my machine only...
    working_dir: "/"
    security_opt:
      - label:disable
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HUGGING_FACE_HUB_TOKEN
      - HF_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - LLAMA_ARG_THREADS=16
      - LLAMA_ARG_ENDPOINT_METRICS=1
    ipc: host
    entrypoint:
      /usr/local/bin/watch-and-restart-llama-swap.sh
    command:
      /configs/llama-swap-config.yaml

  open-webui-demo:
    image: ghcr.io/open-webui/open-webui:main
    environment:
#      - DATA_DIR="/app/backend/data"
      - ENABLE_OLLAMA_API=False
      - ENABLE_OPENAI_API=True
      - OPENAI_API_KEY=sk-empty
      - OPENAI_API_BASE_URL=http://llm-multi-backend:8686/v1
      - DEFAULT_MODELS="openai/exllamav2-Qwen2.5-Coder-14B-Instruct"
      - WEBUI_AUTH=False
      - DEFAULT_USER_ROLE="admin"
      - HOST=0.0.0.0 # 127.0.0.1
      - PORT=33033
    entrypoint:
      bash
    command:
      start.sh
      #-c "while true; do sleep 1; done"
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    # network_mode: host 
    ports:
      - 33033:33033
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/open-webui:/app/backend/data

  open-webui-pipelines:
    image: ghcr.io/open-webui/pipelines:main
    extra_hosts:
      - host.docker.internal:host-gateway
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/open-webui-pipelines:/app/pipelines:rw
