FROM docker.io/nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04

RUN \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update \
    && apt-get -y dist-upgrade \
    && apt-get -y install sudo make curl jq libcurl4-openssl-dev ccache inotify-tools git libssl-dev \
    && curl -Ls https://github.com/Kitware/CMake/releases/download/v4.2.1/cmake-4.2.1-linux-x86_64.tar.gz \
    | tar xz -C /usr/local --strip-components 1 \
    && curl -LsSf https://astral.sh/uv/install.sh | sh \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash \
    && bash -c ". /root/.nvm/nvm.sh && nvm install 24 && which npm"
