# install exllamav3
# RUN \
#     --mount=type=cache,target=/root/.cache/pip,sharing=locked \
#     --mount=type=cache,target=/root/.cache/huggingface,sharing=locked \
#     git clone https://github.com/turboderp-org/exllamav3 /opt/exllamav3 \
#     && cd /opt/exllamav3 \
#     && python3 setup.py build_ext -i \
#     && python3 -m pip install --no-deps --no-build-isolation -e .
