ARG TORCH_CUDA_ARCH_LIST="8.6"
ENV TORCH_CUDA_ARCH_LIST=${TORCH_CUDA_ARCH_LIST}

# MAX_JOBS=1 because OOM crashes whole system... (even then usage peaks around 30GB...),
# see https://github.com/Dao-AILab/flash-attention/pull/2079

RUN \
    --mount=type=cache,target=/root/.ccache,sharing=locked \
    --mount=type=cache,target=/root/.cache/pip,sharing=locked \
    --mount=type=cache,target=/root/.cache/huggingface,sharing=locked \
    python3 -c "import torch; assert torch.cuda.is_available()" \
    && python3 -m pip install --no-build-isolation \
       pandas ninja fastparquet safetensors pygments websockets regex 'numpy<2.3' rich pillow pytest \
    && git clone --branch v2.8.0.post2 https://github.com/Dao-AILab/flash-attention /opt/flash-attention \
    && cd /opt/flash-attention \
    && bash -c 'ulimit -v 42000000; env NVCC_THREADS=1 MAX_JOBS=1 FLASH_ATTN_CUDA_ARCHS=80 PYTORCH_NVCC="ccache nvcc" python3 -m pip install --no-build-isolation .'
    # python3 -m pip install 'torch<2.9' torchvision torchaudio --index-url https://download.pytorch.org/whl/cu129 \


# install exllamav2
# sentencepiece
# /root/.cache/torch_extensions/py312_cu124/exllamav2_ext/exllamav2_ext.so
    # --mount=type=cache,target=/root/.cache/pip,sharing=locked \
    # && env XFORMERS_PT_FLASH_ATTN=0 python3 -m pip install \
    #    'torch<2.9' 'git+https://github.com/facebookresearch/xformers@v0.0.32.post2#egg=xformers' \
    # && python3 -m pip install \
    #    'torch<2.9' 'git+https://github.com/huggingface/transformers' \
    # && python3 -c "import torch; import flash_attn_2_cuda" \

RUN \
    --mount=type=cache,target=/root/.cache/huggingface,sharing=locked \
    python3 -c "import torch; import flash_attn_2_cuda" \
    && git clone https://github.com/turboderp/exllamav2 /opt/exllamav2 \
    && cd /opt/exllamav2 \
    && python3 setup.py build_ext -i \
    && python3 -m pip install --no-deps --no-build-isolation -e .

    # cd /opt/flash-attention \
    # && python3 -m pytest -s -q tests/test_flash_attn.py \
    # && 


RUN \
    --mount=type=cache,target=/root/.cache/pip,sharing=locked \
    --mount=type=cache,target=/root/.cache/huggingface,sharing=locked \
    cd /opt/exllamav2 \
    && if [ ! -d /root/.cache/huggingface/hub/models--turboderp--gpt2-exl2/snapshots/b5411192023974a0c481c71ebda557e3bf9c7ca9 ]; then \
        env HF_HUB_ENABLE_HF_TRANSFER=1 huggingface-cli download turboderp/gpt2-exl2 --revision 3.0bpw; fi \
    && python3 test_inference.py -m /root/.cache/huggingface/hub/models--turboderp--gpt2-exl2/snapshots/b5411192023974a0c481c71ebda557e3bf9c7ca9 -p "A short limmerick: The bear" #|| echo "If you see this, and a complain about no CUDA enabled GPUs, make sure you pass podman build the flag: --device nvidia.com/gpu=all"


#python setup.py build_ext -i \
#    && pip install -e .

RUN \
    --mount=type=cache,target=/root/.cache/pip,sharing=locked \
    git clone https://github.com/theroyallab/tabbyAPI /opt/tabbyAPI \
    && cd /opt/tabbyAPI \
    && python3 -m pip install -e .



# ENV PIP_ROOT_USER_ACTION=ignore
# RUN python3 -m pip install flash-attn qwen-vl-utils[decord] torchvision fastapi uvicorn torch pillow gputil 
