apiRequestTimeout: 1250
modelNameSplitToken: "@"

variants:
  no-think-qwen3:
    tag: "@no-think"
    model-regex: "*[Qq]wen3-*"
    inject-at-end: "\n\n/no_think"
    weak-defaults:
      temperature: 0.7
      top_k: 20
      top_p: 0.8
    thinking:
      strip: true
      tags: ["<think>", "</think>"]
    
  do-think-qwen3:
    tag: "@think"
    model-regex: "*[Qq]wen3-*"
    inject-at-end: "\n\n/think"
    weak-defaults:
      temperature: 0.6
      top_k: 20 
      top_p: 0.95
    thinking:
      strip: false
      tags: ["<think>", "</think>"]

  do-think-silent-qwen3:
    base-off: do-think-qwen3
    name: "@think-silent"
    thinking:
      strip: true
