log_level: "debug"
api_request_timeout_seconds: 1250
split_token_model_name_label: "@"
max_request_bytes: 16777216

variants:
  - name: "do-think-qwen"
    label: "do-think"
    model_regex: ".*[Qq]wen3-.*"
    inject_at_end: "\n\n/think"
    weak_defaults:
      temperature: 0.6
    thinking:
      handling: "DISCARD"
      tag_pair: ["<think>", "</think>"]
      max_chars_before_opening: 8


  - name: "q35-instr"
    label: "instr"
    model_regex: "[Qq]wen3.5-.*"
    strong_overrides:
      chat_template_kwargs:
        enable_thinking: false
      temperature: 0.8
      top_p: 0.9
      presence_penalty: 0.5
      repetition_penalty: 1.05
