  llamacpp-Qwen3-0.6B:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-0.6B.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-0.6B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --ctx-size 32768
        --samplers 'top_k;dry;min_p;temperature;top_p'
        # ^-- vain attempt to capture both thinking/non-thinking
        --min-p 0.005
        --top-p 0.97
        --top-k 40
        --temp 0.7
        --dry-multiplier 0.7
        --dry-allowed-length 4
        --dry-penalty-last-n 2048
        --presence-penalty 0.05
        --frequency-penalty 0.005
        --repeat-penalty 1.01
        --repeat-last-n 16
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-1.7B:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-1.7B.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-1.7B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --ctx-size 32768
        --samplers 'top_k;dry;min_p;temperature;top_p'
        # ^-- vain attempt to capture both thinking/non-thinking
        --min-p 0.005
        --top-p 0.97
        --top-k 40
        --temp 0.7
        --dry-multiplier 0.7
        --dry-allowed-length 4
        --dry-penalty-last-n 2048
        --presence-penalty 0.05
        --frequency-penalty 0.005
        --repeat-penalty 1.01
        --repeat-last-n 16
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-4B:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-4B.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-4B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --ctx-size 32768
        --samplers 'top_k;dry;min_p;temperature;top_p'
        # ^-- vain attempt to capture both thinking/non-thinking
        --min-p 0.005
        --top-p 0.97
        --top-k 40
        --temp 0.7
        --dry-multiplier 0.7
        --dry-allowed-length 4
        --dry-penalty-last-n 2048
        --presence-penalty 0.05
        --frequency-penalty 0.005
        --repeat-penalty 1.01
        --repeat-last-n 16
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-8B:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-8B.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-8B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --ctx-size 32768
        --samplers 'top_k;dry;min_p;temperature;top_p'
        # ^-- vain attempt to capture both thinking/non-thinking
        --min-p 0.005
        --top-p 0.97
        --top-k 40
        --temp 0.7
        --dry-multiplier 0.7
        --dry-allowed-length 4
        --dry-penalty-last-n 2048
        --presence-penalty 0.05
        --frequency-penalty 0.005
        --repeat-penalty 1.01
        --repeat-last-n 16
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-14B:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-14B.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-14B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --cache-type-v q8_0
        --flash-attn
        --ctx-size 32768
        --samplers 'top_k;dry;min_p;temperature;top_p'
        # ^-- vain attempt to capture both thinking/non-thinking
        --min-p 0.005
        --top-p 0.97
        --top-k 40
        --temp 0.7
        --dry-multiplier 0.7
        --dry-allowed-length 4
        --dry-penalty-last-n 2048
        --presence-penalty 0.05
        --frequency-penalty 0.005
        --repeat-penalty 1.01
        --repeat-last-n 16
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-30B-A3B:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-30B-A3B.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-30B-A3B-GGUF:Q4_K_M
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --cache-type-v q8_0
        --flash-attn
        --ctx-size 32768
        --samplers 'top_k;dry;min_p;temperature;top_p'
        # ^-- vain attempt to capture both thinking/non-thinking
        --min-p 0.005
        --top-p 0.97
        --top-k 40
        --temp 0.7
        --dry-multiplier 0.7
        --dry-allowed-length 4
        --dry-penalty-last-n 2048
        --presence-penalty 0.05
        --frequency-penalty 0.005
        --repeat-penalty 1.01
        --repeat-last-n 16
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-32B:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-32B.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-32B-GGUF:Q4_K_M
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --cache-type-v q4_0
        --flash-attn
        --ctx-size 32768
        --samplers 'top_k;dry;min_p;temperature;top_p'
        # ^-- vain attempt to capture both thinking/non-thinking
        --min-p 0.005
        --top-p 0.97
        --top-k 40
        --temp 0.7
        --dry-multiplier 0.7
        --dry-allowed-length 4
        --dry-penalty-last-n 2048
        --presence-penalty 0.05
        --frequency-penalty 0.005
        --repeat-penalty 1.01
        --repeat-last-n 16
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-0.6B-thinking:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-0.6B-thinking.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-0.6B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --ctx-size 32768
        --samplers 'top_k;top_p;min_p;temperature;dry;typ_p'
        --min-p 0.01
        --top-p 0.95
        # ^-- thinking mode, for non-thinking use 0.8
        --top-k 30
        --dry-multiplier 0.5
        --dry-allowed-length 5
        --temp 0.6
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-1.7B-thinking:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-1.7B-thinking.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-1.7B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --ctx-size 32768
        --samplers 'top_k;top_p;min_p;temperature;dry;typ_p'
        --min-p 0.01
        --top-p 0.95
        # ^-- thinking mode, for non-thinking use 0.8
        --top-k 30
        --dry-multiplier 0.5
        --dry-allowed-length 5
        --temp 0.6
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-4B-thinking:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-4B-thinking.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-4B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --ctx-size 32768
        --samplers 'top_k;top_p;min_p;temperature;dry;typ_p'
        --min-p 0.01
        --top-p 0.95
        # ^-- thinking mode, for non-thinking use 0.8
        --top-k 30
        --dry-multiplier 0.5
        --dry-allowed-length 5
        --temp 0.6
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-8B-thinking:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-8B-thinking.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-8B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --ctx-size 32768
        --samplers 'top_k;top_p;min_p;temperature;dry;typ_p'
        --min-p 0.01
        --top-p 0.95
        # ^-- thinking mode, for non-thinking use 0.8
        --top-k 30
        --dry-multiplier 0.5
        --dry-allowed-length 5
        --temp 0.6
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-14B-thinking:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-14B-thinking.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-14B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --cache-type-v q8_0
        --flash-attn
        --ctx-size 32768
        --samplers 'top_k;top_p;min_p;temperature;dry;typ_p'
        --min-p 0.01
        --top-p 0.95
        # ^-- thinking mode, for non-thinking use 0.8
        --top-k 30
        --dry-multiplier 0.5
        --dry-allowed-length 5
        --temp 0.6
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-30B-A3B-thinking:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-30B-A3B-thinking.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-30B-A3B-GGUF:Q4_K_M
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --cache-type-v q8_0
        --flash-attn
        --ctx-size 32768
        --samplers 'top_k;top_p;min_p;temperature;dry;typ_p'
        --min-p 0.01
        --top-p 0.95
        # ^-- thinking mode, for non-thinking use 0.8
        --top-k 30
        --dry-multiplier 0.5
        --dry-allowed-length 5
        --temp 0.6
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-32B-thinking:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-32B-thinking.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-32B-GGUF:Q4_K_M
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --cache-type-v q4_0
        --flash-attn
        --ctx-size 32768
        --samplers 'top_k;top_p;min_p;temperature;dry;typ_p'
        --min-p 0.01
        --top-p 0.95
        # ^-- thinking mode, for non-thinking use 0.8
        --top-k 30
        --dry-multiplier 0.5
        --dry-allowed-length 5
        --temp 0.6
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-0.6B-nonthinking:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-0.6B-nonthinking.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-0.6B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --ctx-size 32768
        --samplers 'top_k;dry;min_p;temperature;top_p'
        --min-p 0.00
        --top-p 0.98
        --top-k 50
        --dry-multiplier 1.1
        --dry-allowed-length 3
        --dry-penalty-last-n 4096
        --presence-penalty 0.15
        --frequency-penalty 0.01
        --temp 1.0
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-1.7B-nonthinking:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-1.7B-nonthinking.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-1.7B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --ctx-size 32768
        --samplers 'top_k;dry;min_p;temperature;top_p'
        --min-p 0.00
        --top-p 0.98
        --top-k 50
        --dry-multiplier 1.1
        --dry-allowed-length 3
        --dry-penalty-last-n 4096
        --presence-penalty 0.15
        --frequency-penalty 0.01
        --temp 1.0
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-4B-nonthinking:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-4B-nonthinking.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-4B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --ctx-size 32768
        --samplers 'top_k;dry;min_p;temperature;top_p'
        --min-p 0.00
        --top-p 0.98
        --top-k 50
        --dry-multiplier 1.1
        --dry-allowed-length 3
        --dry-penalty-last-n 4096
        --presence-penalty 0.15
        --frequency-penalty 0.01
        --temp 1.0
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-8B-nonthinking:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-8B-nonthinking.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-8B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --ctx-size 32768
        --samplers 'top_k;dry;min_p;temperature;top_p'
        --min-p 0.00
        --top-p 0.98
        --top-k 50
        --dry-multiplier 1.1
        --dry-allowed-length 3
        --dry-penalty-last-n 4096
        --presence-penalty 0.15
        --frequency-penalty 0.01
        --temp 1.0
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-14B-nonthinking:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-14B-nonthinking.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-14B-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --cache-type-v q8_0
        --flash-attn
        --ctx-size 32768
        --samplers 'top_k;dry;min_p;temperature;top_p'
        --min-p 0.00
        --top-p 0.98
        --top-k 50
        --dry-multiplier 1.1
        --dry-allowed-length 3
        --dry-penalty-last-n 4096
        --presence-penalty 0.15
        --frequency-penalty 0.01
        --temp 1.0
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-30B-A3B-nonthinking:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-30B-A3B-nonthinking.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-30B-A3B-GGUF:Q4_K_M
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --cache-type-v q8_0
        --flash-attn
        --ctx-size 32768
        --samplers 'top_k;dry;min_p;temperature;top_p'
        --min-p 0.00
        --top-p 0.98
        --top-k 50
        --dry-multiplier 1.1
        --dry-allowed-length 3
        --dry-penalty-last-n 4096
        --presence-penalty 0.15
        --frequency-penalty 0.01
        --temp 1.0
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600

  llamacpp-Qwen3-32B-nonthinking:
    cmd: |
      llama-serve-wrap /logs/llamacpp-Qwen3-32B-nonthinking.log
        --port ${PORT}
        --hf-repo bartowski/Qwen_Qwen3-32B-GGUF:Q4_K_M
        --n-gpu-layers 999
        --jinja
        --cache-type-k q8_0
        --cache-type-v q4_0
        --flash-attn
        --ctx-size 32768
        --samplers 'top_k;dry;min_p;temperature;top_p'
        --min-p 0.00
        --top-p 0.98
        --top-k 50
        --dry-multiplier 1.1
        --dry-allowed-length 3
        --dry-penalty-last-n 4096
        --presence-penalty 0.15
        --frequency-penalty 0.01
        --temp 1.0
    proxy: http://127.0.0.1:${PORT}
    ttl: 3600
