  llamacpp-gemma-3-12b-it:
    cmd: >
      /opt/llama.cpp/build/bin/llama-server
        --log-file /logs/llamacpp-gemma-3-27b-it.log
        --port 8003
        --hf-repo unsloth/gemma-3-12b-it-GGUF:Q6_K_XL
        --n-gpu-layers 999
        # --hf-repo-draft google/gemma-3-1b-it-qat-q4_0-gguf
        # --n-gpu-layers-draft 999
        --jinja
        --ctx-size 21000
        --cache-type-k q8_0
        --cache-type-v q8_0
        --flash-attn
        --samplers "min_p;dry;temperature;top_p" # xtc;
        --min-p 0.03
        --dry-multiplier 0.2
        --dry-allowed-length 3
        --dry-penalty-last-n 256
        --temp 1.0
        --top-p 0.95
    proxy: http://127.0.0.1:8003
    ttl: 3600

  llamacpp-gemma-3-27b-it:
    cmd: >
      /opt/llama.cpp/build/bin/llama-server
        --log-file /logs/llamacpp-gemma-3-27b-it.log
        --port 8003
        --hf-repo google/gemma-3-27b-it-qat-q4_0-gguf
        --n-gpu-layers 999
        # --hf-repo-draft google/gemma-3-1b-it-qat-q4_0-gguf
        # --n-gpu-layers-draft 999
        --jinja
        --ctx-size 21000
        --cache-type-k q8_0
        --cache-type-v q8_0
        --flash-attn
        --samplers "min_p;dry;temperature;top_p" # xtc;
        --min-p 0.03
        --dry-multiplier 0.2
        --dry-allowed-length 3
        --dry-penalty-last-n 256
        --temp 1.0
        --top-p 0.95
    proxy: http://127.0.0.1:8003
    ttl: 3600

  llamacpp-gemma-3-4b-it:
    cmd: >
      /opt/llama.cpp/build/bin/llama-server
        --log-file /logs/llamacpp-gemma-3-4b-it.log
        --port 8004
        --hf-repo google/gemma-3-4b-it-qat-q4_0-gguf # unsloth/gemma-3-4b-it-GGUF:Q4_K_M
        --cache-type-k q4_0
        --cache-type-v q4_0
        --flash-attn
        --n-gpu-layers 999
        --jinja
        --ctx-size 16000
        --temp 1.0
        --prio 2
        --temp 1.0
        --repeat-penalty 1.0
        --min-p 0.01
        --top-k 64
        --top-p 0.95
    proxy: http://127.0.0.1:8004
    ttl: 3600

  llamacpp-gemma-3-1b-it:
    cmd: >
      /opt/llama.cpp/build/bin/llama-server
        --log-file /logs/llamacpp-gemma-3-1b-it.log
        --port 8012
        --hf-repo unsloth/gemma-3-1b-it-GGUF:Q8_0
        --n-gpu-layers 999
        --jinja
        --ctx-size 16000
        --cache-type-k q8_0
        --cache-type-v q5_1
        --flash-attn
        --temp 1.0
        --min-p 0.01
        --top-k 64
        --top-p 0.95
    proxy: http://127.0.0.1:8012
    ttl: 3600
