#!/bin/bash
repo_root="$(cd $(dirname $(realpath "$BASH_SOURCE")); git rev-parse --show-toplevel 2>/dev/null)"
dest="$repo_root/configs/llama-swap-config.yaml"
echo "# This file was generated by $0, do not edit. -*- eval: '(read-only-mode)' -*-" >"$dest"
sed '/^\s*#/d' $repo_root/configs/llama-swap-config-*.yaml >>"$dest"
